### ISSUE TITLE
cannot import name 'thread_pool' from 'src.utils.global_param'

### ISSUE THREAD

**Issue by ifromeast** [agiresearch/AIOS#1]
when run
```
python main.py --llm_name gemma-2b-it
```
the ERROR occurs
```
ImportError: cannot import name 'thread_pool' from 'src.utils.global_param'
```

**Comment by dongyuanjushi** [comment]
Thanks for the attention! 

We have updated the version to fix this. If this error still happens, please let us know.

**Comment by ifromeast** [comment]
hi, there is a new ERROR for the latest code
```
cannot import name 'AgentProcessQueue' from 'src.agents.agent_process'
```

**Comment by ukpark** [comment]
I also had the same issue. You can uncomment lines of  AgentProcessQueue: at src/agent_process.py
