### ISSUE TITLE
Invalid Loads value

### ISSUE THREAD

**Issue by shabbirshuvo** [agiresearch/AIOS#13]
Hi everyone. I am having an issue with GPU memory on a Windows machine when I try to run the code from the terminal of vscode. Tried directly copying the command, and also tried other values, seems nothing is working. What might be the problem?

![image](https://github.com/agiresearch/AIOS/assets/56643245/6b265381-94fe-4d8e-8be8-4f682947c4df)

**Comment by dongyuanjushi** [comment]
Hi, could you provide the detailed procedures to reproduce this error? Thanks. From the screenshot, I guess you do not run the script in a shell environment.
