### ISSUE TITLE
[Usage] AcademicAgent/MathAgent can only use ollama and cannot interact with arxiv or rapidapi

### ISSUE THREAD

**Issue by wawa0210** [agiresearch/AIOS#143]
Similar to the following usage

```bash
python eval.py --llm_name ollama/qwen:7b --agents AcademicAgent:1
```

When using AcademicAgent in the ollama model scenario, I found that the agent can only use llm capabilities and cannot interact with arxiv

Through the dig code, I found that tools are not returned and implemented in the ollama scenario. Is there any potential issue in this?

But I found the corresponding implementation in gpt_llm.py

https://github.com/agiresearch/AIOS/blob/5d849107f9cd6371d1e956e72100b2a9b27ceb8d/src/llm_kernel/llm_classes/ollama_llm.py#L51-L55

https://github.com/agiresearch/AIOS/blob/5d849107f9cd6371d1e956e72100b2a9b27ceb8d/src/llm_kernel/llm_classes/gpt_llm.py#L53-L58

**Comment by dongyuanjushi** [comment]
Please check at the latest version with function calling. Note that current open-sourced LLMs are unstable at calling tools, and we are planning to incorporate more powerful prompting mechanisms to enhance this.
