### ISSUE TITLE
How could an LLM-based OS become reality in the light of non-determinism & hallucination?

### ISSUE THREAD

**Issue by ChristianWeyer** [agiresearch/AIOS#2]
I love the idea!!!

But... how could an LLM-based OS become reality in the light of non-determinism & hallucination?

**Comment by dongyuanjushi** [comment]
Thanks a lot for your attention and recognition.

It's a great question. Actually, we are also working on some controllable mechanisms like control flow, automata to improve the determinism of LLM's each decision. And on the other hand, we imagine that such mechanism may be incorporated into the LLM training to enable LLM to follow instructions more precisely in the future. There is still a long way to go, but we will keep moving towards it.

Best,
