### ISSUE TITLE
[Usage] Issue with AcademicAgent missing aid attribute in example/academic_agent/0.0.1

### ISSUE THREAD

**Issue by XiangZhang-zx** [agiresearch/AIOS#275]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Your current environment

OS: Ubuntu 22.04
Python: 3.10
AIOS Version: Latest
LLM: gemini-1.5-flash

### How would you like to use aios

I want to run AIOS with the LLM endpoint gemini-1.5-flash for the academic_agent. However, I encountered issues where the agent does not run properly

**Comment by dongyuanjushi** [comment]
- Resolve this in this PR (https://github.com/agiresearch/AIOS/pull/276)
