### ISSUE TITLE
[Bug] Need Local Agent Support in manager.py for seeact_agent Testing

### ISSUE THREAD

**Issue by XiangZhang-zx** [agiresearch/AIOS#286]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Describe your current environment

OS: macOS
Python Version: 3.10
AIOS Version: Latest from main branch
No GPU/CUDA requirements for this issue

### Describe the bug

Bug Description
I made a local agent called seeact_agent and got a "successfully set up" message from AIOS. But when I tried to run it, I got an error: This error happens because the framework is set up to only work with agents downloaded from a remote server. It doesn't recognize agents developed on the local machine.

Steps to Reproduce the Bug
Set up a local agent in pyopenagi/agents/example/seeact_agent.
Try to run this local agent through the AIOS framework.
You’ll see an error that says:
File ~/Documents/GitHub/AIOS/pyopenagi/manager/manager.py:94
def _save_agent_to_cache(self, agent_data: Dict, cache_path: Path):
    for file_data in agent_data["files"]:  # KeyError: 'files'
This error stops us from working on the agent locally because the framework is expecting data as if it's coming from an online server.

**Comment by dongyuanjushi** [comment]
I am following up with this. Could you follow the existing adapter like Open-Interpreter adapter to change the interaction function to LLM to send_query function used in AIOS?

**Comment by XiangZhang-zx** [comment]
Thanks! I'll check the Open-Interpreter adapter and try to make seeact_agent work. I'll ask if I need more help.

**Comment by XiangZhang-zx** [comment]
This issue was about local agent support, which was addressed earlier. As of version 0.2.0, this functionality is included. Closing this issue to keep the repository clean.
