### ISSUE TITLE
[Usage] Web Quickstart expects npm to be installed

### ISSUE THREAD

**Issue by dvsLick** [agiresearch/AIOS#289]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Your current environment

fresh raspbian with python 3.11 and all pip requirements

### How would you like to use aios

ran into an issue when booting "launch.py"
![image](https://github.com/user-attachments/assets/a24f7dca-75e7-44c5-9e2b-c5307848f7b7)
easily resolved by installing npm, but this should be mentioned in the installation guide or thrown as a more verbose error

**Comment by dongyuanjushi** [comment]
Thank you for raising this issue. Yes, it is also important to mention this. Could you also update this in both the README.md and the website documentation?

**Comment by dvsLick** [comment]
implemented in [pr 295](https://github.com/agiresearch/AIOS/pull/295)
