### ISSUE TITLE
有个疑问，LLM内核为什么是和OS内核是在同一层上的？ 

### ISSUE THREAD

**Issue by solthx** [agiresearch/AIOS#3]
LLM内核的实现不是基于OS内核完成的么，比如长短期记忆控制的实现、发起外部网络请求等等

**Comment by agiresearch** [comment]
这是个很好的问题，我们也仔细思考过这个问题，我们的看法是在Agent Application的角度来看，可能会有两种并行的请求：对传统OS内核的请求，和对LLM内核的请求，在Agent开发和运行的过程中，这两种请求是并列的、同时发生的，因此我们倾向于让LLM内核和OS内核在同一层

**Comment by solthx** [comment]
感谢回复，我在看代码的时候有个不理解的地方：
<img width="869" alt="image" src="https://github.com/agiresearch/AIOS/assets/27994326/bb422743-ab20-4c99-b766-ba9131a21517">

在回调方法中循环check模型响应相比于以异步回调的方式调用LLM有什么优势么

**Comment by dongyuanjushi** [comment]
感谢您的问题，这个也是我们实际在考虑的，我们目前是按轮询的方式实现的，发现轮询的时间开销可以接受，不过我们也在尝试用异步回调的方式，会进一步对比两种的时间开销选择更优的一种
