### ISSUE TITLE
[Bug] Package Dependencies issue

### ISSUE THREAD

**Issue by subash-19** [agiresearch/AIOS#308]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Describe your current environment

OS - WSL with ubunutu distro  
GPU -  NVIDIA GeForce MX130
Cuda_version - 12.5

### Describe the bug

I created a virtual python environment and installed the packages using "pip install -r requirements.txt". It installed all the packages without any issues. But when I tried to run it its showing missing packages like chromadb, watchdog, llama-index etc. Kindly update the reqirements.txt.

![AIOs(requirements_issue)](https://github.com/user-attachments/assets/9decbd26-ce69-4da3-bce8-8deaace70b18)

**Comment by BRama10** [comment]
@subash-19 thanks for the catch! We'll be updating it soon

**Comment by XiangZhang-zx** [comment]
Hi @subash-19 and @BRama10, I’ve just submitted a PR that addresses the missing dependencies in requirements.txt, adding chromadb, watchdog, and llama-index-embeddings-huggingface. Thanks for bringing up this issue!

**Comment by joshprk** [comment]
Solved with #309
