### ISSUE TITLE
[Usage] Reproduce paper results

### ISSUE THREAD

**Issue by xiaoyu1215** [agiresearch/AIOS#343]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Your current environment

OS: Ubuntu 22.04
Python version: python 3.11.9
CUDA version: cuda 12.1
pytorch version: 2.4.0+cu121

### How would you like to use aios

Hello, authors.
I was recently very interested in AI OS technology and read the paper [https://arxiv.org/abs/2403.16971v3](https://arxiv.org/abs/2403.16971v3). 
It's a very wonderful idea. Thank you very much for your contributions.

I would like to reproduce the results of `section 4` in this paper, but there are many branches to use, which branch can I use?
Please give me some suggestions.
Very grateful to you.

**Comment by dongyuanjushi** [comment]
Thank you for your recognition of our work. It is recommended to use the agent-standard branch and run the scripts under the experiments folder, with use_aios as the arguments to run with/without AIOS of agents.

**Comment by xiaoyu1215** [comment]
> Thank you for your recognition of the work. It is recommended to use the agent-standard branch and run the scripts under the experiments folder, with use_aios as the arguments to run agents with/without AIOS.

Thanks for your recommend.
I had a import error when ran the scripts under experiments folder.  I see some differences between the previous code (about two weeks ago) and the `aios/hoks/syscal.py` file in agent-standard branch (I only checked this file).
Could you give me some advice?


```bash
$ bash experiment/humaneval/bash_with_aios.sh
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/AIOS/experiment/humaneval/inference.py", line 6, in <module>
    from experiment.agent.experiment_agent import ExpirementAgent
  File "/AIOS/experiment/agent/experiment_agent.py", line 3, in <module>
    from aios.hooks.syscall import send_request
ImportError: cannot import name 'send_request' from 'aios.hooks.syscall' (/AIOS/aios/hooks/syscall.py)
```

**Comment by xiaoyu1215** [comment]
> Thank you for your recognition of the work. It is recommended to use the agent-standard branch and run the scripts under the experiments folder, with use_aios as the arguments to run agents with/without AIOS.

hi,  I tried to modify the code to make it run successfully. It does work.
But I encountered a new error: `[rank0]: torch.OutOfMemoryError: CUDA out of memory.`

In the `process_one_func` function of the file `experiment/humaneval/inference.py`, the model is loaded and LLM inference is performed.
In the `run` function of the `experiment/experiment_core.py` file. It seems that the `process_one_func` function is called multiple times depending on the number of data set. 
Does it mean that the model is loaded multiple times? Is this correct? Or am I missing something?
```python
def run(process_one_func, meta_data: MetaData, write_output_func=None):
    total_result = []
    if meta_data.split:
        dataset = meta_data.dataset[meta_data.split]
    else:
        dataset = meta_data.dataset

    for data in tqdm(dataset):
        if meta_data.max_num is not None:
            if meta_data.max_num > 0:
                meta_data.max_num -= 1
            else:
                logger.log(f"Max num {meta_data.max_num} reached", level="info")
                break

        result = process_one_func(data, meta_data)   # call process_one_func() --  [load and inference of LLM]
        total_result.append(result)

    if write_output_func:
        write_output_func(total_result, meta_data.output_file)
    return total_result
```
Is my analysis right?
Please give me some suggestions or some way to fix this bug.

**Comment by dongyuanjushi** [comment]
Yes, the process_one_func could be called multiple times as agents run concurrently. To solve this, it is suggested to adjust the max_worker numbers in the aios.hooks.starter when submitting agents based on your GPU environment.

**Comment by xiaoyu1215** [comment]
Thanks for your response, I'm looking forward to the v0.2.0 release.

**Comment by xiaoyu1215** [comment]
I have a quick question.
In `main.py`, here has so many agent examples. But all the examples have been annotated except for `example/academic_agent`.
I didn't find any other agent implementation in source code (like `example/cocktail_mixlogist`), could you tell me the implementation code for those agents is in which branch or file path?

```python
def main():
    # parse arguments and set configuration for this run accordingly
    main_id = os.getpid()
    print(f"Main ID is: {main_id}")
    warnings.filterwarnings("ignore")
    parser = parse_global_args()
    args = parser.parse_args()
    load_dotenv()

    with aios_starter(**vars(args)) as (submit_agent, await_agent_execution):

        # register your agents and submit agent tasks

        agent_tasks = [
            ["example/academic_agent", "Tell me what is the prollm paper mainly about? "],
            # [
            #     "example/cocktail_mixlogist",
            #     "Create a cocktail for a summer garden party. Guests enjoy refreshing, citrusy flavors. Available ingredients include vodka, gin, lime, lemon, mint, and various fruit juices.",
            # ],
            # [
            #     "example/festival_card_designer",
            #     "Design a festival card for a vintage-themed music festival targeting young adults, with a square card size.",
            # ],
......
```

**Comment by dongyuanjushi** [comment]
> I have a quick question. In `main.py`, here has so many agent examples. But all the examples have been annotated except for `example/academic_agent`. I didn't find any other agent implementation in source code (like `example/cocktail_mixlogist`), could you tell me the implementation code for those agents is in which branch or file path?
> 
> ```python
> def main():
>     # parse arguments and set configuration for this run accordingly
>     main_id = os.getpid()
>     print(f"Main ID is: {main_id}")
>     warnings.filterwarnings("ignore")
>     parser = parse_global_args()
>     args = parser.parse_args()
>     load_dotenv()
> 
>     with aios_starter(**vars(args)) as (submit_agent, await_agent_execution):
> 
>         # register your agents and submit agent tasks
> 
>         agent_tasks = [
>             ["example/academic_agent", "Tell me what is the prollm paper mainly about? "],
>             # [
>             #     "example/cocktail_mixlogist",
>             #     "Create a cocktail for a summer garden party. Guests enjoy refreshing, citrusy flavors. Available ingredients include vodka, gin, lime, lemon, mint, and various fruit juices.",
>             # ],
>             # [
>             #     "example/festival_card_designer",
>             #     "Design a festival card for a vintage-themed music festival targeting young adults, with a square card size.",
>             # ],
> ......
> ```

To maintain a more lightweight github repo, we do not upload all the agent source code here. Instead, we use another agenthub which is deployed on remote to store the agents. And when you uncomment these agents, these agents will be automatically downloaded into your local. Typically, it will be stored in the agenthub/cache/. The pipeline of downloading agents can be found [here](https://aios-3.gitbook.io/aios-docs/aios-agent/how-to-use-agent)
