### ISSUE TITLE
[Bug] [v0.2] AssertionError in aios_demo_concurrent.py with gemini-1.5-flash

### ISSUE THREAD

**Issue by XiangZhang-zx** [agiresearch/AIOS#347]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Describe your current environment

- Python 3.10
- macOS

## Issue
Running `aios_demo_concurrent.py` with `gemini-1.5-flash` results in an AssertionError.

## Steps
1. Clone the v0.2 branch of the repository.
2. Navigate to the `Cerebrum/example` directory.
3. Run the following script:
   ```python
   from cerebrum.example.aios_demo_concurrent import setup_client, run_tasks

   client = setup_client(
       llm_name="gemini-1.5-flash",
       root_dir="root",
       memory_limit=500*1024*1024,
       max_workers=32
   )

   tasks = [
       ["example/academic_agent", {"task": "Summarize AIOS paper"}],
       ["example/academic_agent", {"task": "Find related work to AIOS"}]
   ]

   results = run_tasks(client, tasks, timeout=300)
   ```

## Error
```
AssertionError: Server response for "gemini-1.5-flash" is not as expected.
```

## Expected
Tasks should execute successfully using `gemini-1.5-flash`.
<img width="468" alt="image" src="https://github.com/user-attachments/assets/6a03cf5b-fdeb-40f3-8903-817a5df76106">
<img width="468" alt="image" src="https://github.com/user-attachments/assets/c11dfa01-b19f-4fc3-b5dc-6fc99693eedf">

**Comment by dongyuanjushi** [comment]
Does this just occur in the aios-concurrent demo or it also occurs in the aios-basic-demo?

**Comment by dongyuanjushi** [comment]
Add the llm_backend argument and it should work now. Could you have try that again?

**Comment by XiangZhang-zx** [comment]
The aios_demo_concurrent.py file is no longer in the repository. Closing this issue now. Let me know if further testing is needed elsewhere.
