### ISSUE TITLE
[Bug] 500 Internal Server Error If Missing API Key

### ISSUE THREAD

**Issue by joshprk** [agiresearch/AIOS#356]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Describe your current environment

OS: NixOS 24.11 unstable
GPU: N/A
CUDA: N/A
Python 3.11, venv
Using Cerebrum source (not PyPI version)

### Describe the bug

A 500 internal server error occurs when running the test file in Cerebrum,
upon further investigation, I realized this is because there is no API key--it might be better to panic early if no API key is supplied.

```
INFO:     Application startup complete.
INFO:     127.0.0.1:52452 - "POST /core/llm/setup HTTP/1.1" 500 Internal Server Error
'NoneType' object has no attribute 'stop'
INFO:     127.0.0.1:52458 - "POST /core/cleanup HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44674 - "POST /core/llm/setup HTTP/1.1" 500 Internal Server Error
'NoneType' object has no attribute 'stop'
INFO:     127.0.0.1:44682 - "POST /core/cleanup HTTP/1.1" 500 Internal Server Error
```

**Comment by dongyuanjushi** [comment]
The test file in the cerebrum is deprecated and removed.
