### ISSUE TITLE
[feat] more detailed "500" errors

### ISSUE THREAD

**Issue by om-raheja** [agiresearch/AIOS#365]
I had to uncomment the try catch just to find out that my API key wasn't defined. At least in the server logs for AIOS, please add `print(e)` in `runtime/kernel.py`. I will add this myself if necessary but just wanted to create issue for my own reference.

This seems like a simple fix, but doing this would have saved me ~60 minutes of work over multiple days.

**Comment by dongyuanjushi** [comment]
It is resolved by https://github.com/agiresearch/AIOS/pull/370
