### ISSUE TITLE
[Bug] run-agent Command Unexpectedly Occupies Port 8000 Without Prior Kernel Launch

### ISSUE THREAD

**Issue by XiangZhang-zx** [agiresearch/AIOS#367]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Describe your current environment

macOS
Python 3.10.15

### Describe the bug

When I run the run-agent command, it starts using port 8000 even if I didn't run bash runtime/launch_kernel.sh first. This makes it hard to start the kernel service later.

**Steps to Reproduce**
1. Do not run bash runtime/launch_kernel.sh.
2. Run this command:
   run-agent --llm_name gpt-4o-mini --llm_backend openai --agent_name_or_path demo_author/demo_agent --task "Tell me what is core idea of AIOS" --aios_kernel_url http://localhost:8000
3. The system shows:
   ✅ Client initialized successfully
   Status: {'llm': 'active', 'storage': 'active', 'memory': 'active', 'tool': 'active', 'scheduler': 'active'}
   🚀 Executing agent: demo_agent
   📋 Task: Tell me what is core idea of AIOS
<img width="468" alt="image" src="https://github.com/user-attachments/assets/b6855dc0-7934-48ac-aebf-dc9253d53694">

4. Now try to run bash runtime/launch_kernel.sh.
You see an error:
   ERROR: [Errno 48] error while attempting to bind on address ('127.0.0.1', 8000): address already in use
<img width="468" alt="image" src="https://github.com/user-attachments/assets/93f314ce-c182-46eb-b7c7-7d6527b47ba8">

**Expected Behavior**
The run-agent command should check if the kernel service is running.
If not, it should tell the user to run bash runtime/launch_kernel.sh first.
Or, it should give a clear error message instead of starting the service automatically.
**Actual Behavior**
The run-agent command starts the service and uses port 8000.
There is no clear message or warning.
This makes it impossible to start the kernel service properly.

**Comment by pallavibiswas** [comment]
I was not able to reproduce this, could you please check again?
I used the following command:
``python3.10 run_agent.py --llm_name gemini-1.5-flash --llm_backend google --agent_name_or_path demo_author/demo_agent --task "Tell me what is core idea of AIOS" --aios_kernel_url http://127.0.0.1:8000``

**Comment by XiangZhang-zx** [comment]
Thank you for checking this! The issue seems to be specific to the run-agent command-line tool, not the run_agent.py script.

**Comment by dongyuanjushi** [comment]
Do you still encounter this problem when using the run-agent command?

**Comment by XiangZhang-zx** [comment]
Thank you! Based on the latest tests, this issue has been resolved. The process now stops automatically when it fails to initialize
