### ISSUE TITLE
[Bug] NoneType Error in Agent Status Check

### ISSUE THREAD

**Issue by XiangZhang-zx** [agiresearch/AIOS#368]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Describe your current environment

macOS

Python 3.10.15

### Description
When running math_agent, the system throws `'NoneType' object has no attribute 'replace'` error during agent status checks, despite successful agent download and cache.

### Steps to Reproduce
1. Run math_agent :
run-agent --llm_name gpt-4o-mini --llm_backend openai --agent_name_or_path example/math_agent --task "Expand the expression (3x + 2)(4x - 5)" --aios_kernel_url http://localhost:8000
2. Agent downloads and caches successfully
3. During status check, error occurs

INFO: 127.0.0.1:65511 - "POST /agents/submit HTTP/1.1" 200 OK
Saved agent to cache: /Users/xiangzhang/Library/Caches/cerebrum/example/math_agent/0-0-1.agent
Agent example/math_agent (v0.0.1) downloaded and cached successfully.
Installing dependencies for agent. Writing to /Users/xiangzhang/Library/Caches/cerebrum/example/math_agent/0-0-1.log
'NoneType' object has no attribute 'replace'
INFO: 127.0.0.1:65512 - "GET /agents/420517/status HTTP/1.1" 200 OK
### Expected Behavior
- Agent status check should complete without NoneType errors
- Status should be properly returned

### Actual Behavior
- NoneType error occurs during status check
- Error repeats with subsequent status checks

<img width="711" alt="Screenshot 2024-12-05 at 10 22 18 AM" src="https://github.com/user-attachments/assets/f6b7f863-2d1e-4481-bd14-b67a784176ef">

**Comment by dongyuanjushi** [comment]
Please check the latest version of Cerebrum with the following two PRs
- https://github.com/agiresearch/Cerebrum/pull/11
- https://github.com/agiresearch/Cerebrum/pull/9 

to see whether it has been resolved.

**Comment by XiangZhang-zx** [comment]
The issue has been resolved in my earlier PR. The latest PRs seem to add further improvements. I believe this issue can now be closed.
