### ISSUE TITLE
[Usage] Integration Issues with AutoGen, Open-Interpreter, and MetaGPT in AIOS

### ISSUE THREAD

**Issue by XiangZhang-zx** [agiresearch/AIOS#369]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Your current environment

macOS

Python 3.10.15

### How would you like to use aios

Description:
I'm trying to use AIOS with AutoGen, Open-Interpreter, and MetaGPT, but I'm encountering the following issues:

Missing Imports:
The examples in the documentation don't specify the necessary imports, making it difficult to understand how to get started.
Outdated Documentation:
The docs reference aios_starter, which doesn't appear in the v2.0 codebase. This indicates that the documentation needs an update to reflect the latest code structure.
Additionally, it would be helpful to clarify the usage steps in the documentation for better integration. Let me know if I can assist in identifying other unclear parts.

https://docs.aios.foundation/aios-docs/aios-agent/how-to-develop-agents/develop-with-autogen
https://docs.aios.foundation/aios-docs/aios-agent/how-to-develop-agents/develop-with-open-interpreter
https://docs.aios.foundation/aios-docs/aios-agent/how-to-develop-agents/develop-with-metagpt

**Comment by dongyuanjushi** [comment]
Could you check the updated PR in
- https://github.com/agiresearch/Cerebrum/pull/8

to see whether it can work?

**Comment by XiangZhang-zx** [comment]
I’ve tested the updated PR, and it works perfectly now. Thank you for addressing the issue! Closing this now.
