### ISSUE TITLE
[Bug] http://127.0.0.1:8000 Web showing {"detail":"Not Found"}

### ISSUE THREAD

**Issue by hebiao064** [agiresearch/AIOS#374]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Describe your current environment

Mac OS
Python 3.10

### Describe the bug

After the command:
```
bash runtime/launch_kernel.sh

INFO:     Started server process [169]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```

The page (http://127.0.0.1:8000) showing:
<img width="220" alt="Screenshot 2024-12-08 at 11 57 39 PM" src="https://github.com/user-attachments/assets/452db39a-ce87-44ea-bd6a-9be72ff580c3">

**Comment by dongyuanjushi** [comment]
Do you attempt to open the aios kernel in the browser by clicking the http://127.0.0.1:8000 url? AIOS kernel itself does not intend to show anything in the web browser. It is required to use AIOS SDK(Cerebrum) to interact with the AIOS kernel.

**Comment by hebiao064** [comment]
Yes I thought that would be a valid UI, good to know that.
I'll close it.
