### ISSUE TITLE
[Misc] Discord Invite is Invalid in Firefox

### ISSUE THREAD

**Issue by hariappi** [agiresearch/AIOS#377]
### Anything you want to discuss about aios.

Hi, 
I cannot access discord invite, could you update README with new link.

Thanks

<img width="1390" alt="Screenshot 2024-12-13 at 2 16 04 PM" src="https://github.com/user-attachments/assets/276fc108-a8fa-4d21-b480-16a7489f0e65" />

**Comment by yongfeng101** [comment]
That's strange. I just tested and it works, can you click again?: https://discord.gg/B2HFxEgTJX

If still not working, can you tell us more details such as what browser you are using? Thanks.

**Comment by hariappi** [comment]
Thanks, It is working in chrome but not on firefox.
