### ISSUE TITLE
AIOS SDK是否开源？

### ISSUE THREAD

**Issue by wanbo432503** [agiresearch/AIOS#4]
论文里面有一个表列出了sdk几个接口，但是没有在代码仓里面看到？后续是否有开源计划？

**Comment by dongyuanjushi** [comment]
有开源计划，我们仍在开发与测试中，本项目会长期维护和持续更新，欢迎届时对sdk提建议和使用反馈

**Comment by lumiere-ml** [comment]
有社区吗，想参与开源开发

**Comment by lumiere-ml** [comment]
> 有开源计划，我们仍在开发与测试中，本项目会长期维护和持续更新，欢迎届时对sdk提建议和使用反馈

有社区吗，想参与开源开发

**Comment by dongyuanjushi** [comment]
Thanks for your interest. Feel free to join the discord shown in README.md. More timely updates and discussions can be found there.
