### ISSUE TITLE
What is the difference between FIFO and Fixed-order execution

### ISSUE THREAD

**Issue by ShangwenWang** [agiresearch/AIOS#56]
Dear authors,

After reading the code, I had a question that I did not undersatnd clearly.

I note that you used the concurrent.futures module to implement the FIFO schedule. Then, each thread is the execution of agent.run function. Since you define all the necessary actions to finish an agent's task in the run function (e.g., the travel agent https://github.com/agiresearch/AIOS/blob/79eb091ae050de86313b173cccc1c40849074b1a/src/agents/travel_agent/travel_agent.py#L46), I wonder what is the differences between the FIFO schedule and the fixed execution order? In other words, why these two ways have different efficiency results as reported in the paper. 

I would greatly appreciate it if you could help me.
Thanks in advance.

**Comment by ShangwenWang** [comment]
I previously imagined that the schadule is based on each step of agents, but it seems not. If this is the case, in the run function, the prompt should be added into the thread pool after each round, am I right?

**Comment by dongyuanjushi** [comment]
The fixed-order execution of agents in our experiments is that Agent A will have all of its steps executed and then Agent B can be then executed. We design the scheduler to consider the situation where multiple agents could run concurrently or in the future in parallel. Putting all the prompt steps from different agents in a list and then enumerating the prompts and executing can be hard to extend with the increase of agent numbers. So we design this scheduler to concurrently do this.

**Comment by dongyuanjushi** [comment]
Each request of an agent is scheduled by calling the get_response function, where thread is used for each agent request sent to the LLM.

**Comment by ShangwenWang** [comment]
Could you please give a detailed example about the execution order of agents under the FIFO schedule? IMHO, the FIFO means the first agent request will be executed until it is finished, unless there is an interrupt. However, I did not find the interrupt in the code, which means the next request will wait for the finish of its previous request. This leads to the same execution result of fixed-order.

**Comment by dongyuanjushi** [comment]
Take agent A,B,C for example, A has 3 steps: A1, A2, A3, B has 2 steps: B1, B2, C has two steps: C1, C2. With FIFO, the execution order can be A1, B1, C1, A2, B2, A3, C2 (can vary due to the request arriving time). And the fixed order should be A1, A2, A3, B1, B2, C1, C2.

**Comment by ShangwenWang** [comment]
Oh I see. So my initial thought was right, the schedule is performed based on the step granularity. One more question would be there is no get_response function in the travel agent.

**Comment by dongyuanjushi** [comment]
Oh thanks. The travel agent is currently under construction and it is supposed to be moved into the native-agent branch. It will be fixed.
