### ISSUE TITLE
Issues with Module Path and SDKs in the paper

### ISSUE THREAD

**Issue by Conless** [agiresearch/AIOS#7]
I'm interested about your idea to integrate LLM agent into operating system, but I came across several problems when running your project.

1. Incorrect imported module path in `travel_agents.py`. You may change
    ```py
    from src.tools.bing_search import BingSearch
    from src.tools.google_search import GoogleSearch
    from src.tools.arxiv import Arxiv
    ```
    to 
    ```py
    from src.tools.online.bing_search import BingSearch
    from src.tools.online.google_search import GoogleSearch
    from src.tools.online.arxiv import Arxiv
    ```
2. I didn't find the SDKs and syscalls mentioned in the paper, so I don't know how to test applications on your project. Have you thought about make these modules open-source later?

Thank you for your hard work on this project, and I look forward to your response and guidance on these matters.

**Comment by dongyuanjushi** [comment]
Thanks a lot for bringing the problems. The module import error of travel_agent is fixed. We are actively developing and testing the syscall and SDKs, they will be open-sourced in the updated version. Suggestions and pull requests are alway welcome!
